Task4 Changes
scutt5/fullstack-starter pull request #4
Opened 2024-11-21 01:16 UTC by scutt5

Here are the changes for Task 4. Thanks!

2024-11-21 01:48 UTC, JeremiahFailla requested changes
Looks mostly good just some minor feedback. Also missing the unit tests.

2024-11-21 01:48 UTC, JeremiahFailla commented on starter/src/main/java/com/starter/fullstack/rest/InventoryController.java
> +
remove empty line

2024-11-21 01:48 UTC, JeremiahFailla commented on starter/src/main/java/com/starter/fullstack/rest/InventoryController.java
> +    //else is empty
remove comment

2024-11-21 02:03 UTC, scutt5 commented
Should have the missing unit tests now and the previous feedback.

2024-11-21 02:20 UTC, JeremiahFailla requested changes
Minor feedback

2024-11-21 02:20 UTC, JeremiahFailla commented on starter/src/main/java/com/starter/fullstack/rest/InventoryController.java
> +
looks like you still have this empty line. Please remove it. There shouldn't be any empty lines in your imports. Can you also remove the empty line you have in the imports in InventoryDAO.java

2024-11-21 02:20 UTC, JeremiahFailla commented on starter/src/test/java/com/starter/fullstack/rest/InventoryControllerTest.java
> +        .content("[\"" + this.inventory.getId() + "\"]"))
This should be a single id not a list

2024-11-21 02:20 UTC, JeremiahFailla commented on starter/src/main/java/com/starter/fullstack/rest/InventoryController.java
> +    //else is empty
Dont forget to remove this comment

2024-11-23 00:43 UTC, JeremiahFailla approved these changes

2024-11-24 19:22 UTC, merged